include: package:very_good_analysis/analysis_options.4.0.0.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - build/**

  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    avoid_redundant_argument_values: false
    avoid_positional_boolean_parameters: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false

custom_lint:
  incremental: true
